version: 2.1
orbs:
  bc-orb: evrons/bc-orb@0.0.2
  orb-tools: circleci/orb-tools@9.0
parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"
executors:
  default:
    docker:
      - image: python
jobs:
  integration-test-1:
    executor: default
    steps:
      - checkout
      - bc-orb/greet:
          greeting: "allahu akbar"
      - bc-orb/install
      - bc-orb/checkov:
          path: "."
workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: evrons/bc-orb
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-1
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: evrons/bc-orb
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          publish-version-tag: false
          requires:
            - integration-test-1
          filters:
            branches:
              only: master
